export class DeliveryBookingModel {

    DeliveryBookingId: number;
    OrderId: number;
    ContainsAlcohol: boolean;
    BookingDate: Date;
    DropoffContactName: string;
    DropoffAddress: string;
    DropoffEmail: string;
    DropoffFirstName: string;
    DropoffLastName: string;
    DropoffDetAddress: object;
    Customer: object;
    DropoffTime: Date;
    DropoffContactMobile: string;
    DropoffNotification: boolean;
    DropoffInstructions: string;
    PickupContactName: string;
    PickupAddress: string;
    PickupDetAddress: object;
    PickupTime: Date;
    PickupInstructions: string;
    PickupContactMobile: string;
    PickupTimeEstimated: Date;
    PickupTimeActual: Date;
    DropoffTimeEstimated: Date;
    DropoffTimeActual: Date;
    ExternalDeliveryId: string;
    ExternalBusinessName: string;
    ExternalStoreId: string;
    Tip: string;
    DriverName: string;
    DriverContact: string;
    BookingReference: string;
    IsContactLess: boolean;
    CurrentStatus: string;
    CancelReason: string;
    OrderValue: string;
    DeliveryTime: string;
    OrderNumValue: number;
    DropoffStreet: string;
    DropoffStreetNumber: string;
    PickupStreetNumber: string;
    PickupStreet: string;
    PickupState: string;
    PickupCity: string;
    PickupZipCode: string;
    PickupUnit: string;
    DropoffUnit: string;
    DropoffState: string;
    DropoffCity: string;
    DropoffZipCode: string;
    DeliveryPartnerId: number;
    Fee: number;
    DropoffEta: Date;
    DeliveryPartnerName: string;
    QuoteId: string;
    SherpaDeliveryoption: string;
    DoordashFee: number;
    DoordashDropoffEta: Date;
    DoordashQuoteId: number;
    Expires: Date;
    ChangeDetPickupAddress: boolean;
    ChangeDetDropoffAddress: boolean;
    DropoffLatitude: number;
    DropoffLongitude: number;
    PickupLatitude: number;
    PickupLongitude: number;

    constructor(deliveryModel?) {
        deliveryModel = deliveryModel || {};
        this.DoordashFee = deliveryModel.DoordashFee || 0;
        this.DoordashDropoffEta = deliveryModel.DoordashDropoffEta || null;
        this.DoordashQuoteId = deliveryModel.DoordashQuoteId || 0;
        this.QuoteId = deliveryModel.QuoteId || "";
        this.DeliveryBookingId = deliveryModel.DeliveryBookingId || 0;
        this.OrderId = deliveryModel.OrderId || 0;
        this.BookingDate = deliveryModel.BookingDate || null;
        this.ContainsAlcohol = deliveryModel.ContainsAlcohol || false;
        this.ExternalDeliveryId = deliveryModel.ExternalDeliveryId || "";
        this.ExternalStoreId = deliveryModel.ExternalStoreId || "";
        this.ExternalBusinessName = deliveryModel.ExternalBusinessName || "";
        this.DeliveryTime = deliveryModel.DeliveryTime || "";
        this.DropoffContactName = deliveryModel.DropoffContactName || "";
        this.DropoffAddress = deliveryModel.DropoffAddress || "";
        this.DropoffContactMobile = deliveryModel.DropoffContactMobile || "";
        this.DropoffNotification = deliveryModel.DropoffNotification || false;
        this.DropoffInstructions = deliveryModel.DropoffInstructions || " ";
        this.BookingReference = deliveryModel.BookingReference || " ";
        this.OrderValue = deliveryModel.OrderValue || " ";
        this.OrderNumValue = deliveryModel.OrderNumValue || 0;
        this.PickupDetAddress = deliveryModel.PickupDetAddress || {};
        this.PickupStreet = deliveryModel.PickupStreet || '';
        this.PickupStreetNumber = deliveryModel.PickupStreetNumber || '';
        this.PickupUnit = deliveryModel.PickupUnit || '';
        this.DropoffUnit = deliveryModel.DropoffUnit || '';
        this.DropoffStreet = deliveryModel.DropoffStreet || '';
        this.DropoffStreetNumber = deliveryModel.DropoffStreetNumber || '';
        this.DropoffFirstName = deliveryModel.DropoffFirstName || " ";
        this.DropoffLastName = deliveryModel.DropoffLastName || " ";
        this.DropoffEmail = deliveryModel.DropoffEmail || " ";
        this.DropoffDetAddress = deliveryModel.DropoffDetAddress || {};
        this.Customer = deliveryModel.Customer || {};
        this.SherpaDeliveryoption = deliveryModel.sherpadeliveryOption || "";

        this.PickupZipCode = deliveryModel.PickupZipCode || "";
        this.PickupContactName = deliveryModel.PickupContactName || "";
        this.PickupAddress = deliveryModel.PickupAddress || "";
        this.DropoffZipCode = deliveryModel.DropoffZipCode || "";
        this.PickupTime = deliveryModel.PickupTime;
        this.PickupState = deliveryModel.PickupState || "";
        this.PickupCity = deliveryModel.PickupCity || "";
        this.DropoffState = deliveryModel.DropoffState || "";
        this.DropoffCity = deliveryModel.DropoffCity || "";
        this.PickupInstructions = deliveryModel.PickupInstructions || " ";
        this.PickupContactMobile = deliveryModel.PickupContactMobile || "";
        this.PickupTimeEstimated = deliveryModel.PickupTimeEstimated || null;
        this.PickupTimeActual = deliveryModel.PickupTimeActual || null;
        this.DropoffTimeEstimated = deliveryModel.DropoffTimeEstimated || null;
        this.DropoffTimeActual = deliveryModel.DropoffTimeActual || null;

        this.DriverContact = deliveryModel.DriverContact || "";
        this.DriverName = deliveryModel.DriverName || "";
        this.CurrentStatus = deliveryModel.CurrentStatus || "";
        this.CancelReason = deliveryModel.CancelReason || "";
        this.IsContactLess = deliveryModel.IsContactLess || false;
        this.DropoffTime = deliveryModel.DropoffTime;
        this.DeliveryPartnerId = deliveryModel.DeliveryPartnerId || 0;
        this.Fee = deliveryModel.Fee || 0;
        this.DropoffEta = deliveryModel.DropoffEta || null;
        this.DeliveryPartnerName = deliveryModel.DeliveryPartnerName || "";
        this.Expires = deliveryModel.Expires || null;
        this.DropoffLatitude = deliveryModel.DropoffLatitude || 0;
        this.DropoffLongitude = deliveryModel.DropoffLongitude || 0;
        this.PickupLatitude = deliveryModel.PickupLatitude || 0;
        this.PickupLongitude = deliveryModel.PickupLongitude || 0;

        this.ChangeDetPickupAddress = deliveryModel.ChangeDetPickupAddress || false;
        this.ChangeDetDropoffAddress = deliveryModel.ChangeDetDropoffAddress || false;
    }
}