export class CityDb {
    public static city: any = [
        {
            "id": "1",
            "city": "Port Denison",
            "country": "Australia",
            "lat": "-29.2828",
            "lng": "114.9166",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1213"
        },
        {
            "id": "2",
            "city": "Kwinana",
            "country": "Australia",
            "lat": "-32.2394",
            "lng": "115.7702",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "20086"
        },
        {
            "id": "3",
            "city": "Port Hedland",
            "country": "Australia",
            "lat": "-20.3104",
            "lng": "118.606",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "14288"
        },
        {
            "id": "4",
            "city": "Busselton",
            "country": "Australia",
            "lat": "-33.6564",
            "lng": "115.3487",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "10214"
        },
        {
            "id": "5",
            "city": "Esperance",
            "country": "Australia",
            "lat": "-33.8573",
            "lng": "121.8889",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "7888"
        },
        {
            "id": "6",
            "city": "Exmouth",
            "country": "Australia",
            "lat": "-21.9311",
            "lng": "114.1233",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1085"
        },
        {
            "id": "7",
            "city": "Morawa",
            "country": "Australia",
            "lat": "-29.2163",
            "lng": "116",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "259"
        },
        {
            "id": "8",
            "city": "Laverton",
            "country": "Australia",
            "lat": "-28.627",
            "lng": "122.404",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "316"
        },
        {
            "id": "9",
            "city": "Leonara",
            "country": "Australia",
            "lat": "-28.8815",
            "lng": "121.328",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "227"
        },
        {
            "id": "10",
            "city": "Norseman",
            "country": "Australia",
            "lat": "-32.2",
            "lng": "121.7666",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1004"
        },
        {
            "id": "11",
            "city": "Katanning",
            "country": "Australia",
            "lat": "-33.6996",
            "lng": "117.5501",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "3934"
        },
        {
            "id": "12",
            "city": "Southern Cross",
            "country": "Australia",
            "lat": "-31.2161",
            "lng": "119.3167",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "187"
        },
        {
            "id": "13",
            "city": "Halls Creek",
            "country": "Australia",
            "lat": "-18.2667",
            "lng": "127.7667",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1209"
        },
        {
            "id": "14",
            "city": "Pannawonica",
            "country": "Australia",
            "lat": "-21.6366",
            "lng": "116.325",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "686"
        },
        {
            "id": "15",
            "city": "Tom Price",
            "country": "Australia",
            "lat": "-22.6935",
            "lng": "117.7931",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "2723"
        },
        {
            "id": "16",
            "city": "Albany",
            "country": "Australia",
            "lat": "-35.0169",
            "lng": "117.8916",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "26445"
        },
        {
            "id": "17",
            "city": "Perth",
            "country": "Australia",
            "lat": "-31.955",
            "lng": "115.84",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1532000"
        },
        {
            "id": "18",
            "city": "Narrogin",
            "country": "Australia",
            "lat": "-32.9329",
            "lng": "117.1666",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "4238"
        },
        {
            "id": "19",
            "city": "Broome",
            "country": "Australia",
            "lat": "-17.9618",
            "lng": "122.2308",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "13218"
        },
        {
            "id": "20",
            "city": "Bunbury",
            "country": "Australia",
            "lat": "-33.3443",
            "lng": "115.6502",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "26998"
        },
        {
            "id": "21",
            "city": "Wyndham",
            "country": "Australia",
            "lat": "-15.374",
            "lng": "128.3601",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "800"
        },
        {
            "id": "22",
            "city": "Roebourne",
            "country": "Australia",
            "lat": "-20.7829",
            "lng": "117.1333",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "19260"
        },
        {
            "id": "23",
            "city": "Carnarvon",
            "country": "Australia",
            "lat": "-24.8998",
            "lng": "113.6501",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "7392"
        },
        {
            "id": "24",
            "city": "Kalbarri",
            "country": "Australia",
            "lat": "-27.6662",
            "lng": "114.1667",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1537"
        },
        {
            "id": "25",
            "city": "Kununurra",
            "country": "Australia",
            "lat": "-15.7666",
            "lng": "128.7333",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "5679"
        },
        {
            "id": "26",
            "city": "Manjimup",
            "country": "Australia",
            "lat": "-34.2333",
            "lng": "116.15",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "4240"
        },
        {
            "id": "27",
            "city": "Mandurah",
            "country": "Australia",
            "lat": "-32.5235",
            "lng": "115.7471",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "73356"
        },
        {
            "id": "28",
            "city": "Karratha",
            "country": "Australia",
            "lat": "-20.7304",
            "lng": "116.87",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "16796"
        },
        {
            "id": "29",
            "city": "Geraldton",
            "country": "Australia",
            "lat": "-28.7666",
            "lng": "114.6",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "27258"
        },
        {
            "id": "30",
            "city": "Onslow",
            "country": "Australia",
            "lat": "-21.6576",
            "lng": "115.0963",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "573"
        },
        {
            "id": "31",
            "city": "Mount Barker",
            "country": "Australia",
            "lat": "-34.6328",
            "lng": "117.6666",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1781"
        },
        {
            "id": "32",
            "city": "Mount Magnet",
            "country": "Australia",
            "lat": "-28.0662",
            "lng": "117.8167",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "424"
        },
        {
            "id": "33",
            "city": "Ravensthorpe",
            "country": "Australia",
            "lat": "-33.5829",
            "lng": "120.0333",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1101"
        },
        {
            "id": "34",
            "city": "Gingin",
            "country": "Australia",
            "lat": "-31.3496",
            "lng": "115.9",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1446"
        },
        {
            "id": "35",
            "city": "Meekatharra",
            "country": "Australia",
            "lat": "-26.6",
            "lng": "118.4833",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "654"
        },
        {
            "id": "36",
            "city": "Northam",
            "country": "Australia",
            "lat": "-31.6566",
            "lng": "116.6534",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "5855"
        },
        {
            "id": "37",
            "city": "Merredin",
            "country": "Australia",
            "lat": "-31.4828",
            "lng": "118.2667",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "2668"
        },
        {
            "id": "38",
            "city": "Three Springs",
            "country": "Australia",
            "lat": "-29.5333",
            "lng": "115.75",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "190"
        },
        {
            "id": "39",
            "city": "Wagin",
            "country": "Australia",
            "lat": "-33.2996",
            "lng": "117.35",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "1598"
        },
        {
            "id": "40",
            "city": "Newman",
            "country": "Australia",
            "lat": "-23.3666",
            "lng": "119.7333",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "5138"
        },
        {
            "id": "41",
            "city": "Kalgoorlie",
            "country": "Australia",
            "lat": "-30.7354",
            "lng": "121.46",
            "iso2": "AU",
            "iso3": "AUS",
            "state_name": "Western Australia",
            "population": "36852"
        }
    ]
}