export class CountryDb {
    id: any;
    name: string;
    public static country: any = [
        { 'id': 1, 'name': 'Afghanistan', 'code': 'AF' },
        { 'id': 2, 'name': 'Åland Islands', 'code': 'AX' },
        { 'id': 3, 'name': 'Albania', 'code': 'AL' },
        { 'id': 4, 'name': 'Algeria', 'code': 'DZ' },
        { 'id': 5, 'name': 'American Samoa', 'code': 'AS' },
        { 'id': 6, 'name': 'AndorrA', 'code': 'AD' },
        { 'id': 7, 'name': 'Angola', 'code': 'AO' },
        { 'id': 8, 'name': 'Anguilla', 'code': 'AI' },
        { 'id': 9, 'name': 'Antarctica', 'code': 'AQ' },
        { 'id': 10, 'name': 'Antigua and Barbuda', 'code': 'AG' },
        { 'id': 11, 'name': 'Argentina', 'code': 'AR' },
        { 'id': 12, 'name': 'Armenia', 'code': 'AM' },
        { 'id': 13, 'name': 'Aruba', 'code': 'AW' },
        { 'id': 14, 'name': 'Australia', 'code': 'AU' },
        { 'id': 15, 'name': 'Austria', 'code': 'AT' },
        { 'id': 16, 'name': 'Azerbaijan', 'code': 'AZ' },
        { 'id': 17, 'name': 'Bahamas', 'code': 'BS' },
        { 'id': 18, 'name': 'Bahrain', 'code': 'BH' },
        { 'id': 19, 'name': 'Bangladesh', 'code': 'BD' },
        { 'id': 20, 'name': 'Barbados', 'code': 'BB' },
        { 'id': 21, 'name': 'Belarus', 'code': 'BY' },
        { 'id': 22, 'name': 'Belgium', 'code': 'BE' },
        { 'id': 23, 'name': 'Belize', 'code': 'BZ' },
        { 'id': 24, 'name': 'Benin', 'code': 'BJ' },
        { 'id': 25, 'name': 'Bermuda', 'code': 'BM' },
        { 'id': 26, 'name': 'Bhutan', 'code': 'BT' },
        { 'id': 27, 'name': 'Bolivia', 'code': 'BO' },
        { 'id': 28, 'name': 'Bosnia and Herzegovina', 'code': 'BA' },
        { 'id': 30, 'name': 'Botswana', 'code': 'BW' },
        { 'id': 31, 'name': 'Bouvet Island', 'code': 'BV' },
        { 'id': 32, 'name': 'Brazil', 'code': 'BR' },
        { 'id': 34, 'name': 'British Indian Ocean Territory', 'code': 'IO' },
        { 'id': 35, 'name': 'Brunei Darussalam', 'code': 'BN' },
        { 'id': 36, 'name': 'Bulgaria', 'code': 'BG' },
        { 'id': 37, 'name': 'Burkina Faso', 'code': 'BF' },
        { 'id': 38, 'name': 'Burundi', 'code': 'BI' },
        { 'id': 39, 'name': 'Cambodia', 'code': 'KH' },
        { 'id': 40, 'name': 'Cameroon', 'code': 'CM' },
        { 'id': 41, 'name': 'Canada', 'code': 'CA' },
        { 'id': 42, 'name': 'Cape Verde', 'code': 'CV' },
        { 'id': 43, 'name': 'Cayman Islands', 'code': 'KY' },
        { 'id': 44, 'name': 'Central African Republic', 'code': 'CF' },
        { 'id': 45, 'name': 'Chad', 'code': 'TD' },
        { 'id': 46, 'name': 'Chile', 'code': 'CL' },
        { 'id': 47, 'name': 'China', 'code': 'CN' },
        { 'id': 48, 'name': 'Christmas Island', 'code': 'CX' },
        { 'id': 49, 'name': 'Cocos (Keeling) Islands', 'code': 'CC' },
        { 'id': 50, 'name': 'Colombia', 'code': 'CO' },
        { 'id': 51, 'name': 'Comoros', 'code': 'KM' },
        { 'id': 52, 'name': 'Congo', 'code': 'CG' },
        { 'id': 53, 'name': 'Congo, The Democratic Republic of the', 'code': 'CD' },
        { 'id': 54, 'name': 'Cook Islands', 'code': 'CK' },
        { 'id': 56, 'name': 'Costa Rica', 'code': 'CR' },
        { 'id': 57, 'name': 'Cote D\'Ivoire', 'code': 'CI' },
        { 'id': 58, 'name': 'Croatia', 'code': 'HR' },
        { 'id': 59, 'name': 'Cuba', 'code': 'CU' },
        { 'id': 60, 'name': 'Cyprus', 'code': 'CY' },
        { 'id': 61, 'name': 'Czech Republic', 'code': 'CZ' },
        { 'id': 62, 'name': 'Denmark', 'code': 'DK' },
        { 'id': 63, 'name': 'Djibouti', 'code': 'DJ' },
        { 'id': 64, 'name': 'Dominica', 'code': 'DM' },
        { 'id': 65, 'name': 'Dominican Republic', 'code': 'DO' },
        { 'id': 66, 'name': 'Ecuador', 'code': 'EC' },
        { 'id': 67, 'name': 'Egypt', 'code': 'EG' },
        { 'id': 68, 'name': 'El Salvador', 'code': 'SV' },
        { 'id': 69, 'name': 'Equatorial Guinea', 'code': 'GQ' },
        { 'id': 70, 'name': 'Eritrea', 'code': 'ER' },
        { 'id': 71, 'name': 'Estonia', 'code': 'EE' },
        { 'id': 72, 'name': 'Ethiopia', 'code': 'ET' },
        { 'id': 73, 'name': 'Falkland Islands (Malvinas)', 'code': 'FK' },
        { 'id': 74, 'name': 'Faroe Islands', 'code': 'FO' },
        { 'id': 75, 'name': 'Fiji', 'code': 'FJ' },
        { 'id': 76, 'name': 'Finland', 'code': 'FI' },
        { 'id': 77, 'name': 'France', 'code': 'FR' },
        { 'id': 78, 'name': 'French Guiana', 'code': 'GF' },
        { 'id': 79, 'name': 'French Polynesia', 'code': 'PF' },
        { 'id': 80, 'name': 'French Southern Territories', 'code': 'TF' },
        { 'id': 81, 'name': 'Gabon', 'code': 'GA' },
        { 'id': 82, 'name': 'Gambia', 'code': 'GM' },
        { 'id': 83, 'name': 'Georgia', 'code': 'GE' },
        { 'id': 84, 'name': 'Germany', 'code': 'DE' },
        { 'id': 85, 'name': 'Ghana', 'code': 'GH' },
        { 'id': 86, 'name': 'Gibraltar', 'code': 'GI' },
        { 'id': 87, 'name': 'Greece', 'code': 'GR' },
        { 'id': 88, 'name': 'Greenland', 'code': 'GL' },
        { 'id': 89, 'name': 'Grenada', 'code': 'GD' },
        { 'id': 90, 'name': 'Guadeloupe', 'code': 'GP' },
        { 'id': 91, 'name': 'Guam', 'code': 'GU' },
        { 'id': 92, 'name': 'Guatemala', 'code': 'GT' },
        { 'id': 93, 'name': 'Guernsey', 'code': 'GG' },
        { 'id': 94, 'name': 'Guinea', 'code': 'GN' },
        { 'id': 95, 'name': 'Guinea-Bissau', 'code': 'GW' },
        { 'id': 96, 'name': 'Guyana', 'code': 'GY' },
        { 'id': 97, 'name': 'Haiti', 'code': 'HT' },
        { 'id': 98, 'name': 'Heard Island and Mcdonald Islands', 'code': 'HM' },
        { 'id': 99, 'name': 'Holy See (Vatican City State)', 'code': 'VA' },
        { 'id': 100, 'name': 'Honduras', 'code': 'HN' },
        { 'id': 101, 'name': 'Hong Kong', 'code': 'HK' },
        { 'id': 102, 'name': 'Hungary', 'code': 'HU' },
        { 'id': 103, 'name': 'Iceland', 'code': 'IS' },
        { 'id': 104, 'name': 'India', 'code': 'IN' },
        { 'id': 105, 'name': 'Indonesia', 'code': 'ID' },
        { 'id': 106, 'name': 'Iran, Islamic Republic Of', 'code': 'IR' },
        { 'id': 107, 'name': 'Iraq', 'code': 'IQ' },
        { 'id': 108, 'name': 'Ireland', 'code': 'IE' },
        { 'id': 109, 'name': 'Isle of Man', 'code': 'IM' },
        { 'id': 110, 'name': 'Israel', 'code': 'IL' },
        { 'id': 111, 'name': 'Italy', 'code': 'IT' },
        { 'id': 112, 'name': 'Jamaica', 'code': 'JM' },
        { 'id': 113, 'name': 'Japan', 'code': 'JP' },
        { 'id': 114, 'name': 'Jersey', 'code': 'JE' },
        { 'id': 115, 'name': 'Jordan', 'code': 'JO' },
        { 'id': 116, 'name': 'Kazakhstan', 'code': 'KZ' },
        { 'id': 117, 'name': 'Kenya', 'code': 'KE' },
        { 'id': 118, 'name': 'Kiribati', 'code': 'KI' },
        { 'id': 119, 'name': 'Korea, Democratic People\'S Republic of', 'code': 'KP' },
        { 'id': 120, 'name': 'Korea, Republic of', 'code': 'KR' },
        { 'id': 121, 'name': 'Kuwait', 'code': 'KW' },
        { 'id': 122, 'name': 'Kyrgyzstan', 'code': 'KG' },
        { 'id': 123, 'name': 'Lao People\'S Democratic Republic', 'code': 'LA' },
        { 'id': 124, 'name': 'Latvia', 'code': 'LV' },
        { 'id': 125, 'name': 'Lebanon', 'code': 'LB' },
        { 'id': 126, 'name': 'Lesotho', 'code': 'LS' },
        { 'id': 127, 'name': 'Liberia', 'code': 'LR' },
        { 'id': 128, 'name': 'Libyan Arab Jamahiriya', 'code': 'LY' },
        { 'id': 129, 'name': 'Liechtenstein', 'code': 'LI' },
        { 'id': 130, 'name': 'Lithuania', 'code': 'LT' },
        { 'id': 131, 'name': 'Luxembourg', 'code': 'LU' },
        { 'id': 132, 'name': 'Macao', 'code': 'MO' },
        { 'id': 133, 'name': 'Macedonia, The Former Yugoslav Republic of', 'code': 'MK' },
        { 'id': 134, 'name': 'Madagascar', 'code': 'MG' },
        { 'id': 135, 'name': 'Malawi', 'code': 'MW' },
        { 'id': 136, 'name': 'Malaysia', 'code': 'MY' },
        { 'id': 137, 'name': 'Maldives', 'code': 'MV' },
        { 'id': 138, 'name': 'Mali', 'code': 'ML' },
        { 'id': 139, 'name': 'Malta', 'code': 'MT' },
        { 'id': 140, 'name': 'Marshall Islands', 'code': 'MH' },
        { 'id': 141, 'name': 'Martinique', 'code': 'MQ' },
        { 'id': 142, 'name': 'Mauritania', 'code': 'MR' },
        { 'id': 143, 'name': 'Mauritius', 'code': 'MU' },
        { 'id': 144, 'name': 'Mayotte', 'code': 'YT' },
        { 'id': 145, 'name': 'Mexico', 'code': 'MX' },
        { 'id': 146, 'name': 'Micronesia, Federated States of', 'code': 'FM' },
        { 'id': 147, 'name': 'Moldova, Republic of', 'code': 'MD' },
        { 'id': 148, 'name': 'Monaco', 'code': 'MC' },
        { 'id': 149, 'name': 'Mongolia', 'code': 'MN' },
        { 'id': 150, 'name': 'Montserrat', 'code': 'MS' },
        { 'id': 151, 'name': 'Morocco', 'code': 'MA' },
        { 'id': 152, 'name': 'Mozambique', 'code': 'MZ' },
        { 'id': 153, 'name': 'Myanmar', 'code': 'MM' },
        { 'id': 154, 'name': 'Namibia', 'code': 'NA' },
        { 'id': 155, 'name': 'Nauru', 'code': 'NR' },
        { 'id': 156, 'name': 'Nepal', 'code': 'NP' },
        { 'id': 157, 'name': 'Netherlands', 'code': 'NL' },
        { 'id': 158, 'name': 'Netherlands Antilles', 'code': 'AN' },
        { 'id': 159, 'name': 'New Caledonia', 'code': 'NC' },
        { 'id': 160, 'name': 'New Zealand', 'code': 'NZ' },
        { 'id': 161, 'name': 'Nicaragua', 'code': 'NI' },
        { 'id': 162, 'name': 'Niger', 'code': 'NE' },
        { 'id': 163, 'name': 'Nigeria', 'code': 'NG' },
        { 'id': 164, 'name': 'Niue', 'code': 'NU' },
        { 'id': 165, 'name': 'Norfolk Island', 'code': 'NF' },
        { 'id': 166, 'name': 'Northern Mariana Islands', 'code': 'MP' },
        { 'id': 167, 'name': 'Norway', 'code': 'NO' },
        { 'id': 168, 'name': 'Oman', 'code': 'OM' },
        { 'id': 169, 'name': 'Pakistan', 'code': 'PK' },
        { 'id': 170, 'name': 'Palau', 'code': 'PW' },
        { 'id': 171, 'name': 'Palestinian Territory, Occupied', 'code': 'PS' },
        { 'id': 172, 'name': 'Panama', 'code': 'PA' },
        { 'id': 178, 'name': 'Papua New Guinea', 'code': 'PG' },
        { 'id': 179, 'name': 'Paraguay', 'code': 'PY' },
        { 'id': 180, 'name': 'Peru', 'code': 'PE' },
        { 'id': 181, 'name': 'Philippines', 'code': 'PH' },
        { 'id': 182, 'name': 'Pitcairn', 'code': 'PN' },
        { 'id': 183, 'name': 'Poland', 'code': 'PL' },
        { 'id': 184, 'name': 'Portugal', 'code': 'PT' },
        { 'id': 185, 'name': 'Puerto Rico', 'code': 'PR' },
        { 'id': 186, 'name': 'Qatar', 'code': 'QA' },
        { 'id': 187, 'name': 'Reunion', 'code': 'RE' },
        { 'id': 188, 'name': 'Romania', 'code': 'RO' },
        { 'id': 189, 'name': 'Russian Federation', 'code': 'RU' },
        { 'id': 190, 'name': 'RWANDA', 'code': 'RW' },
        { 'id': 191, 'name': 'Saint Helena', 'code': 'SH' },
        { 'id': 192, 'name': 'Saint Kitts and Nevis', 'code': 'KN' },
        { 'id': 193, 'name': 'Saint Lucia', 'code': 'LC' },
        { 'id': 194, 'name': 'Saint Pierre and Miquelon', 'code': 'PM' },
        { 'id': 195, 'name': 'Saint Vincent and the Grenadines', 'code': 'VC' },
        { 'id': 196, 'name': 'Samoa', 'code': 'WS' },
        { 'id': 197, 'name': 'San Marino', 'code': 'SM' },
        { 'id': 198, 'name': 'Sao Tome and Principe', 'code': 'ST' },
        { 'id': 199, 'name': 'Saudi Arabia', 'code': 'SA' },
        { 'id': 200, 'name': 'Senegal', 'code': 'SN' },
        { 'id': 201, 'name': 'Serbia and Montenegro', 'code': 'CS' },
        { 'id': 202, 'name': 'Seychelles', 'code': 'SC' },
        { 'id': 203, 'name': 'Sierra Leone', 'code': 'SL' },
        { 'id': 204, 'name': 'Singapore', 'code': 'SG' },
        { 'id': 205, 'name': 'Slovakia', 'code': 'SK' },
        { 'id': 206, 'name': 'Slovenia', 'code': 'SI' },
        { 'id': 207, 'name': 'Solomon Islands', 'code': 'SB' },
        { 'id': 208, 'name': 'Somalia', 'code': 'SO' },
        { 'id': 209, 'name': 'South Africa', 'code': 'ZA' },
        { 'id': 210, 'name': 'South Georgia and the South Sandwich Islands', 'code': 'GS' },
        { 'id': 211, 'name': 'Spain', 'code': 'ES' },
        { 'id': 212, 'name': 'Sri Lanka', 'code': 'LK' },
        { 'id': 213, 'name': 'Sudan', 'code': 'SD' },
        { 'id': 214, 'name': 'Suriname', 'code': 'SR' },
        { 'id': 215, 'name': 'Svalbard and Jan Mayen', 'code': 'SJ' },
        { 'id': 216, 'name': 'Swaziland', 'code': 'SZ' },
        { 'id': 217, 'name': 'Sweden', 'code': 'SE' },
        { 'id': 218, 'name': 'Switzerland', 'code': 'CH' },
        { 'id': 219, 'name': 'Syrian Arab Republic', 'code': 'SY' },
        { 'id': 220, 'name': 'Taiwan, Province of China', 'code': 'TW' },
        { 'id': 221, 'name': 'Tajikistan', 'code': 'TJ' },
        { 'id': 222, 'name': 'Tanzania, United Republic of', 'code': 'TZ' },
        { 'id': 223, 'name': 'Thailand', 'code': 'TH' },
        { 'id': 224, 'name': 'Timor-Leste', 'code': 'TL' },
        { 'id': 225, 'name': 'Togo', 'code': 'TG' },
        { 'id': 226, 'name': 'Tokelau', 'code': 'TK' },
        { 'id': 227, 'name': 'Tonga', 'code': 'TO' },
        { 'id': 228, 'name': 'Trinidad and Tobago', 'code': 'TT' },
        { 'id': 229, 'name': 'Tunisia', 'code': 'TN' },
        { 'id': 230, 'name': 'Turkey', 'code': 'TR' },
        { 'id': 231, 'name': 'Turkmenistan', 'code': 'TM' },
        { 'id': 232, 'name': 'Turks and Caicos Islands', 'code': 'TC' },
        { 'id': 233, 'name': 'Tuvalu', 'code': 'TV' },
        { 'id': 234, 'name': 'Uganda', 'code': 'UG' },
        { 'id': 235, 'name': 'Ukraine', 'code': 'UA' },
        { 'id': 236, 'name': 'United Arab Emirates', 'code': 'AE' },
        { 'id': 237, 'name': 'United Kingdom', 'code': 'GB' },
        { 'id': 238, 'name': 'United States', 'code': 'US' },
        { 'id': 239, 'name': 'United States Minor Outlying Islands', 'code': 'UM' },
        { 'id': 240, 'name': 'Uruguay', 'code': 'UY' },
        { 'id': 241, 'name': 'Uzbekistan', 'code': 'UZ' },
        { 'id': 242, 'name': 'Vanuatu', 'code': 'VU' },
        { 'id': 243, 'name': 'Venezuela', 'code': 'VE' },
        { 'id': 244, 'name': 'Viet Nam', 'code': 'VN' },
        { 'id': 245, 'name': 'Virgin Islands, British', 'code': 'VG' },
        { 'id': 246, 'name': 'Virgin Islands, U.S.', 'code': 'VI' },
        { 'id': 247, 'name': 'Wallis and Futuna', 'code': 'WF' },
        { 'id': 248, 'name': 'Western Sahara', 'code': 'EH' },
        { 'id': 249, 'name': 'Yemen', 'code': 'YE' },
        { 'id': 250, 'name': 'Zambia', 'code': 'ZM' },
        { 'id': 251, 'name': 'Zimbabwe', 'code': 'ZW' }
        // { name: 'Afghanistan', code: 'AF' },
        // { name: 'Åland Islands', code: 'AX' },
        // { name: 'Albania', code: 'AL' },
        // { name: 'Algeria', code: 'DZ' },
        // { name: 'American Samoa', code: 'AS' },
        // { name: 'AndorrA', code: 'AD' },
        // { name: 'Angola', code: 'AO' },
        // { name: 'Anguilla', code: 'AI' },
        // { name: 'Antarctica', code: 'AQ' },
        // { name: 'Antigua and Barbuda', code: 'AG' },
        // { name: 'Argentina', code: 'AR' },
        // { name: 'Armenia', code: 'AM' },
        // { name: 'Aruba', code: 'AW' },
        // { name: 'Australia', code: 'AU' },
        // { name: 'Austria', code: 'AT' },
        // { name: 'Azerbaijan', code: 'AZ' },
        // { name: 'Bahamas', code: 'BS' },
        // { name: 'Bahrain', code: 'BH' },
        // { name: 'Bangladesh', code: 'BD' },
        // { name: 'Barbados', code: 'BB' },
        // { name: 'Belarus', code: 'BY' },
        // { name: 'Belgium', code: 'BE' },
        // { name: 'Belize', code: 'BZ' },
        // { name: 'Benin', code: 'BJ' },
        // { name: 'Bermuda', code: 'BM' },
        // { name: 'Bhutan', code: 'BT' },
        // { name: 'Bolivia', code: 'BO' },
        // { name: 'Bosnia and Herzegovina', code: 'BA' },
        // { name: 'Botswana', code: 'BW' },
        // { name: 'Bouvet Island', code: 'BV' },
        // { name: 'Brazil', code: 'BR' },
        // { name: 'British Indian Ocean Territory', code: 'IO' },
        // { name: 'Brunei Darussalam', code: 'BN' },
        // { name: 'Bulgaria', code: 'BG' },
        // { name: 'Burkina Faso', code: 'BF' },
        // { name: 'Burundi', code: 'BI' },
        // { name: 'Cambodia', code: 'KH' },
        // { name: 'Cameroon', code: 'CM' },
        // { name: 'Canada', code: 'CA' },
        // { name: 'Cape Verde', code: 'CV' },
        // { name: 'Cayman Islands', code: 'KY' },
        // { name: 'Central African Republic', code: 'CF' },
        // { name: 'Chad', code: 'TD' },
        // { name: 'Chile', code: 'CL' },
        // { name: 'China', code: 'CN' },
        // { name: 'Christmas Island', code: 'CX' },
        // { name: 'Cocos (Keeling) Islands', code: 'CC' },
        // { name: 'Colombia', code: 'CO' },
        // { name: 'Comoros', code: 'KM' },
        // { name: 'Congo', code: 'CG' },
        // { name: 'Congo, The Democratic Republic of the', code: 'CD' },
        // { name: 'Cook Islands', code: 'CK' },
        // { name: 'Costa Rica', code: 'CR' },
        // { name: 'Cote D\'Ivoire', code: 'CI' },
        // { name: 'Croatia', code: 'HR' },
        // { name: 'Cuba', code: 'CU' },
        // { name: 'Cyprus', code: 'CY' },
        // { name: 'Czech Republic', code: 'CZ' },
        // { name: 'Denmark', code: 'DK' },
        // { name: 'Djibouti', code: 'DJ' },
        // { name: 'Dominica', code: 'DM' },
        // { name: 'Dominican Republic', code: 'DO' },
        // { name: 'Ecuador', code: 'EC' },
        // { name: 'Egypt', code: 'EG' },
        // { name: 'El Salvador', code: 'SV' },
        // { name: 'Equatorial Guinea', code: 'GQ' },
        // { name: 'Eritrea', code: 'ER' },
        // { name: 'Estonia', code: 'EE' },
        // { name: 'Ethiopia', code: 'ET' },
        // { name: 'Falkland Islands (Malvinas)', code: 'FK' },
        // { name: 'Faroe Islands', code: 'FO' },
        // { name: 'Fiji', code: 'FJ' },
        // { name: 'Finland', code: 'FI' },
        // { name: 'France', code: 'FR' },
        // { name: 'French Guiana', code: 'GF' },
        // { name: 'French Polynesia', code: 'PF' },
        // { name: 'French Southern Territories', code: 'TF' },
        // { name: 'Gabon', code: 'GA' },
        // { name: 'Gambia', code: 'GM' },
        // { name: 'Georgia', code: 'GE' },
        // { name: 'Germany', code: 'DE' },
        // { name: 'Ghana', code: 'GH' },
        // { name: 'Gibraltar', code: 'GI' },
        // { name: 'Greece', code: 'GR' },
        // { name: 'Greenland', code: 'GL' },
        // { name: 'Grenada', code: 'GD' },
        // { name: 'Guadeloupe', code: 'GP' },
        // { name: 'Guam', code: 'GU' },
        // { name: 'Guatemala', code: 'GT' },
        // { name: 'Guernsey', code: 'GG' },
        // { name: 'Guinea', code: 'GN' },
        // { name: 'Guinea-Bissau', code: 'GW' },
        // { name: 'Guyana', code: 'GY' },
        // { name: 'Haiti', code: 'HT' },
        // { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
        // { name: 'Holy See (Vatican City State)', code: 'VA' },
        // { name: 'Honduras', code: 'HN' },
        // { name: 'Hong Kong', code: 'HK' },
        // { name: 'Hungary', code: 'HU' },
        // { name: 'Iceland', code: 'IS' },
        // { name: 'India', code: 'IN' },
        // { name: 'Indonesia', code: 'ID' },
        // { name: 'Iran, Islamic Republic Of', code: 'IR' },
        // { name: 'Iraq', code: 'IQ' },
        // { name: 'Ireland', code: 'IE' },
        // { name: 'Isle of Man', code: 'IM' },
        // { name: 'Israel', code: 'IL' },
        // { name: 'Italy', code: 'IT' },
        // { name: 'Jamaica', code: 'JM' },
        // { name: 'Japan', code: 'JP' },
        // { name: 'Jersey', code: 'JE' },
        // { name: 'Jordan', code: 'JO' },
        // { name: 'Kazakhstan', code: 'KZ' },
        // { name: 'Kenya', code: 'KE' },
        // { name: 'Kiribati', code: 'KI' },
        // { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
        // { name: 'Korea, Republic of', code: 'KR' },
        // { name: 'Kuwait', code: 'KW' },
        // { name: 'Kyrgyzstan', code: 'KG' },
        // { name: 'Lao People\'S Democratic Republic', code: 'LA' },
        // { name: 'Latvia', code: 'LV' },
        // { name: 'Lebanon', code: 'LB' },
        // { name: 'Lesotho', code: 'LS' },
        // { name: 'Liberia', code: 'LR' },
        // { name: 'Libyan Arab Jamahiriya', code: 'LY' },
        // { name: 'Liechtenstein', code: 'LI' },
        // { name: 'Lithuania', code: 'LT' },
        // { name: 'Luxembourg', code: 'LU' },
        // { name: 'Macao', code: 'MO' },
        // { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
        // { name: 'Madagascar', code: 'MG' },
        // { name: 'Malawi', code: 'MW' },
        // { name: 'Malaysia', code: 'MY' },
        // { name: 'Maldives', code: 'MV' },
        // { name: 'Mali', code: 'ML' },
        // { name: 'Malta', code: 'MT' },
        // { name: 'Marshall Islands', code: 'MH' },
        // { name: 'Martinique', code: 'MQ' },
        // { name: 'Mauritania', code: 'MR' },
        // { name: 'Mauritius', code: 'MU' },
        // { name: 'Mayotte', code: 'YT' },
        // { name: 'Mexico', code: 'MX' },
        // { name: 'Micronesia, Federated States of', code: 'FM' },
        // { name: 'Moldova, Republic of', code: 'MD' },
        // { name: 'Monaco', code: 'MC' },
        // { name: 'Mongolia', code: 'MN' },
        // { name: 'Montserrat', code: 'MS' },
        // { name: 'Morocco', code: 'MA' },
        // { name: 'Mozambique', code: 'MZ' },
        // { name: 'Myanmar', code: 'MM' },
        // { name: 'Namibia', code: 'NA' },
        // { name: 'Nauru', code: 'NR' },
        // { name: 'Nepal', code: 'NP' },
        // { name: 'Netherlands', code: 'NL' },
        // { name: 'Netherlands Antilles', code: 'AN' },
        // { name: 'New Caledonia', code: 'NC' },
        // { name: 'New Zealand', code: 'NZ' },
        // { name: 'Nicaragua', code: 'NI' },
        // { name: 'Niger', code: 'NE' },
        // { name: 'Nigeria', code: 'NG' },
        // { name: 'Niue', code: 'NU' },
        // { name: 'Norfolk Island', code: 'NF' },
        // { name: 'Northern Mariana Islands', code: 'MP' },
        // { name: 'Norway', code: 'NO' },
        // { name: 'Oman', code: 'OM' },
        // { name: 'Pakistan', code: 'PK' },
        // { name: 'Palau', code: 'PW' },
        // { name: 'Palestinian Territory, Occupied', code: 'PS' },
        // { name: 'Panama', code: 'PA' },
        // { name: 'Papua New Guinea', code: 'PG' },
        // { name: 'Paraguay', code: 'PY' },
        // { name: 'Peru', code: 'PE' },
        // { name: 'Philippines', code: 'PH' },
        // { name: 'Pitcairn', code: 'PN' },
        // { name: 'Poland', code: 'PL' },
        // { name: 'Portugal', code: 'PT' },
        // { name: 'Puerto Rico', code: 'PR' },
        // { name: 'Qatar', code: 'QA' },
        // { name: 'Reunion', code: 'RE' },
        // { name: 'Romania', code: 'RO' },
        // { name: 'Russian Federation', code: 'RU' },
        // { name: 'RWANDA', code: 'RW' },
        // { name: 'Saint Helena', code: 'SH' },
        // { name: 'Saint Kitts and Nevis', code: 'KN' },
        // { name: 'Saint Lucia', code: 'LC' },
        // { name: 'Saint Pierre and Miquelon', code: 'PM' },
        // { name: 'Saint Vincent and the Grenadines', code: 'VC' },
        // { name: 'Samoa', code: 'WS' },
        // { name: 'San Marino', code: 'SM' },
        // { name: 'Sao Tome and Principe', code: 'ST' },
        // { name: 'Saudi Arabia', code: 'SA' },
        // { name: 'Senegal', code: 'SN' },
        // { name: 'Serbia and Montenegro', code: 'CS' },
        // { name: 'Seychelles', code: 'SC' },
        // { name: 'Sierra Leone', code: 'SL' },
        // { name: 'Singapore', code: 'SG' },
        // { name: 'Slovakia', code: 'SK' },
        // { name: 'Slovenia', code: 'SI' },
        // { name: 'Solomon Islands', code: 'SB' },
        // { name: 'Somalia', code: 'SO' },
        // { name: 'South Africa', code: 'ZA' },
        // { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
        // { name: 'Spain', code: 'ES' },
        // { name: 'Sri Lanka', code: 'LK' },
        // { name: 'Sudan', code: 'SD' },
        // { name: 'Suriname', code: 'SR' },
        // { name: 'Svalbard and Jan Mayen', code: 'SJ' },
        // { name: 'Swaziland', code: 'SZ' },
        // { name: 'Sweden', code: 'SE' },
        // { name: 'Switzerland', code: 'CH' },
        // { name: 'Syrian Arab Republic', code: 'SY' },
        // { name: 'Taiwan, Province of China', code: 'TW' },
        // { name: 'Tajikistan', code: 'TJ' },
        // { name: 'Tanzania, United Republic of', code: 'TZ' },
        // { name: 'Thailand', code: 'TH' },
        // { name: 'Timor-Leste', code: 'TL' },
        // { name: 'Togo', code: 'TG' },
        // { name: 'Tokelau', code: 'TK' },
        // { name: 'Tonga', code: 'TO' },
        // { name: 'Trinidad and Tobago', code: 'TT' },
        // { name: 'Tunisia', code: 'TN' },
        // { name: 'Turkey', code: 'TR' },
        // { name: 'Turkmenistan', code: 'TM' },
        // { name: 'Turks and Caicos Islands', code: 'TC' },
        // { name: 'Tuvalu', code: 'TV' },
        // { name: 'Uganda', code: 'UG' },
        // { name: 'Ukraine', code: 'UA' },
        // { name: 'United Arab Emirates', code: 'AE' },
        // { name: 'United Kingdom', code: 'GB' },
        // { name: 'United States', code: 'US' },
        // { name: 'United States Minor Outlying Islands', code: 'UM' },
        // { name: 'Uruguay', code: 'UY' },
        // { name: 'Uzbekistan', code: 'UZ' },
        // { name: 'Vanuatu', code: 'VU' },
        // { name: 'Venezuela', code: 'VE' },
        // { name: 'Viet Nam', code: 'VN' },
        // { name: 'Virgin Islands, British', code: 'VG' },
        // { name: 'Virgin Islands, U.S.', code: 'VI' },
        // { name: 'Wallis and Futuna', code: 'WF' },
        // { name: 'Western Sahara', code: 'EH' },
        // { name: 'Yemen', code: 'YE' },
        // { name: 'Zambia', code: 'ZM' },
        // { name: 'Zimbabwe', code: 'ZW' }
    ]
}
