export class ProductDb {
    public static product: any = [
        {
            id: '1',
            productid: '1',
            name: 'Tablet 1',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'capsule.jpg',
            isactive: true,
            categoryid: '1',
            createdby: '1',
            information: 'Tablet For Pain',
            instock: true,
            benefits: 'Instant Relief From Pain',
            usage: 'test',
            storage: 'Cool Area',
            activeMaterialId: '2',

        },
        {
            id: '2',
            productid: '2',
            name: 'Tablet 2',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'capsule.jpg',
            isactive: true,
            categoryid: '1',
            createdby: '1',
            information: 'Tablet For Diabates',
            instock: true,
            benefits: 'Control Diabates',
            usage: 'test',
            storage: 'Cool Area',
            activeMaterialId: '2',

        },
        {
            id: '3',
            productid: '3',
            name: 'Napkin',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'Sebamed-baby-products.jpg',
            isactive: true,
            categoryid: '2',
            createdby: '2',
            information: 'Baby Napkins 1',
            instock: true,
            benefits: 'Secure Baby',
            usage: 'test',
            storage: 'Dry Area',
            activeMaterialId: '2',
        },
        {
            id: '4',
            productid: '4',
            name: 'Baby Powder',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'Sebamed-baby-products.jpg',
            isactive: true,
            categoryid: '2',
            createdby: '2',
            information: 'Baby Powder For Fresheness',
            instock: true,
            benefits: 'Secure Baby',
            usage: 'test',
            storage: 'Dry Area',
            activeMaterialId: '2',

        },
        {
            id: '4',
            productid: '4',
            name: 'Baby Powder',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'Sebamed-baby-products.jpg',
            isactive: true,
            categoryid: '2',
            createdby: '2',
            information: 'Baby Powder For Fresheness',
            instock: true,
            benefits: 'Secure Baby',
            usage: 'test',
            storage: 'Dry Area',
            activeMaterialId: '2',

        },
        {
            id: '4',
            productid: '4',
            name: 'Baby Powder',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'Sebamed-baby-products.jpg',
            isactive: true,
            categoryid: '2',
            createdby: '2',
            information: 'Baby Powder For Fresheness',
            instock: true,
            benefits: 'Secure Baby',
            usage: 'test',
            storage: 'Dry Area',
            activeMaterialId: '2',

        },
        {
            id: '4',
            productid: '4',
            name: 'Baby Powder',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'Sebamed-baby-products.jpg',
            isactive: true,
            categoryid: '2',
            createdby: '2',
            information: 'Baby Powder For Fresheness',
            instock: true,
            benefits: 'Secure Baby',
            usage: 'test',
            storage: 'Dry Area',
            activeMaterialId: '2',

        },
        {
            id: '4',
            productid: '4',
            name: 'Baby Powder',
            buyPrice: '10',
            sellPrice: '15',
            discount: 10,
            image: 'Sebamed-baby-products.jpg',
            isactive: true,
            categoryid: '2',
            createdby: '2',
            information: 'Baby Powder For Fresheness',
            instock: true,
            benefits: 'Secure Baby',
            usage: 'test',
            storage: 'Dry Area',
            activeMaterialId: '2',

        }

    ]

}