export class PharmacyModel {
    PharmacyId: number;
    PharmacyName: string;
    PharmacyGrpId: number;
    ContactPersonName: string;
    ActivationDate: string;
    Email1: string;
    Email2: string;
    Phoneno1: string;
    Phoneno2: string;
    Address: string;
    City: string;
    StateId: number;
    CountryId: number;
    Pincode: string;
    FaxId: string;
    VersionNo: string;
    ModifiedOn: Date;
    CreatedOn: Date;
    ServiceFee: number;
    StoreId: string;
    DeliveryCharge: number;
    CreateOrderDeliveryFee: number;
    Latitude: number;
    Longitude: number;
    OpeningHours: string;
    ClosingHours: string;
    ServingId: number;
    Days: string;
    OpeningFormat: string;
    ClosingFormat: Date;
    pharmacyserve_list: any;
    pharmacyserve_list2: any;
    pharmacyGroup: any;
    CreatedBy: number;
    pharmacyServingsList: any;
    pharmacyServingsList2: any;
    AvailablePickup: boolean;
    AvailableDelivery: boolean;
    AvailableServices: Number;
    ConvenienceFee: Number;
    ReturnPrescriptionFee: Number;
    StripeConnectId: string;
    IsPharmacyDelivery: boolean;
    PaymentProcessingFee: string;
    OFees: string;
    PerScriptFee: Number;
    TransactionFee: Number;
    PharmacyOffSet: Number;
    PharmacyLogo: any;
    PharmacyLogoName: any;
    QrCode: string;
    QrCodeTelehealthBooking: string;
    EncodePharmacyName: string;
    StripeDetailsubmitted: string;
    StripeBankDetailsubmitted: string;

    OnDemandPrice: number;
    MedicalCertificatePrice: number;
    OnDemandCode: string;
    MedicalCertificateCode: string;
    WosQrCode: string;
    OTCDB: number;
    DoorDashStoreId: string;
    UberEatsStoreId: string;
    IsDDOnline: boolean;
    IsUEOnline: boolean;
    DDOTCPercentage: Number;
    UEOTCPercentage: Number;
    IsDD: boolean;
    IsUE: boolean;
    DDOnlineReasonId: Number;
    LongDistanceDeliveryFee: number;
    VendorId: string;

    constructor(PharmacyModel?) {
        PharmacyModel = PharmacyModel || {};
        this.DDOnlineReasonId = PharmacyModel.DDOnlineReasonId || 0;
        this.OTCDB = PharmacyModel.OTCDB || 0;
        this.DoorDashStoreId = PharmacyModel.DoorDashStoreId || '';
        this.UberEatsStoreId = PharmacyModel.UberEatsStoreId || '';
        this.OnDemandPrice = PharmacyModel.OnDemandPrice || "";
        this.MedicalCertificatePrice = PharmacyModel.MedicalCertificatePrice || "";
        this.OnDemandCode = PharmacyModel.OnDemandCode || "";
        this.MedicalCertificateCode = PharmacyModel.MedicalCertificateCode || "";
        this.WosQrCode = PharmacyModel.WosQrCode || "";
        this.QrCode = PharmacyModel.QrCode || "";
        this.QrCodeTelehealthBooking = PharmacyModel.QrCodeTelehealthBooking || "";
        this.EncodePharmacyName = PharmacyModel.EncodePharmacyName || "";
        this.PharmacyOffSet = PharmacyModel.PharmacyOffSet || null;
        this.pharmacyGroup = PharmacyModel.pharmacyGroup || [];
        this.pharmacyserve_list = PharmacyModel.pharmacyserve_list || [];
        this.pharmacyserve_list2 = PharmacyModel.pharmacyserve_list2 || [];
        this.PharmacyId = PharmacyModel.PharmacyId || 0;
        this.PharmacyName = PharmacyModel.PharmacyName || '';
        this.PharmacyGrpId = PharmacyModel.PharmacyGrpId || null;
        this.ContactPersonName = PharmacyModel.ContactPersonName || '';
        this.Email1 = PharmacyModel.Email1 || '';
        this.Email2 = PharmacyModel.Email2 || '';
        this.Phoneno1 = PharmacyModel.Phoneno1 || '';
        this.Phoneno2 = PharmacyModel.Phoneno2 || '';
        this.Address = PharmacyModel.Address || '';
        this.City = PharmacyModel.City || '';
        this.StateId = PharmacyModel.StateId || 0;
        this.CountryId = PharmacyModel.CountryId || 0;
        this.AvailableServices = PharmacyModel.AvailableServices || 0;
        this.Pincode = PharmacyModel.Pincode || '';
        this.FaxId = PharmacyModel.FaxId || '';
        this.StoreId = PharmacyModel.StoreId || '';
        this.VersionNo = PharmacyModel.VersionNo || '';
        this.OpeningHours = PharmacyModel.OpeningHours || '';
        this.ClosingHours = PharmacyModel.ClosingHours || '';
        this.ModifiedOn = PharmacyModel.ModifiedOn || new Date();
        this.CreatedOn = PharmacyModel.CreatedOn || new Date();
        this.ServiceFee = PharmacyModel.ServiceFee || 0;
        this.Latitude = PharmacyModel.Latitude || '';
        this.Longitude = PharmacyModel.Longitude || '';
        // this.PharmacyNotes = PharmacyModel.PharmacyNotes || '';
        this.ConvenienceFee = PharmacyModel.ConvenienceFee || .99;
        this.ReturnPrescriptionFee = PharmacyModel.ReturnPrescriptionFee || "";
        this.StripeConnectId = PharmacyModel.StripeConnectId || '';
        this.PaymentProcessingFee = PharmacyModel.PaymentProcessingFee || '';
        this.TransactionFee = PharmacyModel.TransactionFee || 0;
        this.OFees = PharmacyModel.OFees || "";
        this.PerScriptFee = PharmacyModel.PerScriptFee || 0;
        this.ServingId = PharmacyModel.ServingId || 0;
        this.Days = PharmacyModel.Days || '';
        this.IsPharmacyDelivery = PharmacyModel.IsPharmacyDelivery || false;
        this.AvailablePickup = PharmacyModel.AvailablePickup || false;
        this.AvailableDelivery = PharmacyModel.AvailableDelivery || false;
        this.DeliveryCharge = PharmacyModel.DeliveryCharge || 0;
        this.CreateOrderDeliveryFee = PharmacyModel.CreateOrderDeliveryFee || 0;
        this.OpeningFormat = PharmacyModel.OpeningFormat || '';
        this.ClosingFormat = PharmacyModel.ClosingFormat || '';
        this.CreatedBy = PharmacyModel.CreatedBy || 0;
        this.pharmacyServingsList = PharmacyModel.pharmacyServingsList;
        this.pharmacyServingsList2 = PharmacyModel.pharmacyServingsList2;
        this.PharmacyLogo = PharmacyModel.PharmacyLogo || '';
        this.PharmacyLogoName = PharmacyModel.PharmacyLogoName || '';
        this.StripeDetailsubmitted = PharmacyModel.StripeDetailsubmitted;
        this.StripeBankDetailsubmitted = PharmacyModel.StripeBankDetailsubmitted;
        this.IsDDOnline = PharmacyModel.IsDDOnline || false;
        this.IsUEOnline = PharmacyModel.IsUEOnline || false;
        this.DDOTCPercentage = PharmacyModel.DDOTCPercentage || null;
        this.UEOTCPercentage = PharmacyModel.UEOTCPercentage || null;
        this.IsDD = PharmacyModel.IsDD || false;
        this.IsUE = PharmacyModel.IsUE || false;
        this.LongDistanceDeliveryFee = PharmacyModel.LongDistanceDeliveryFee || 0;
        this.VendorId = PharmacyModel.VendorId || '';
    }

}