export class CreateOrderModel {
    FirstName: string;
    LastName: string;
    CustomerId: number;
    MobileNo: string;
    EmailId: string;
    MedicareNo: string;
    Dob: Date;
    Age: number;
    MedicareValidTo: Date;
    ConcessionValidTo: Date;
    OrderType: number;
    IsPreferredPharmacy: number;
    IsDefault: number;
    DeliveryByDate: Date;
    DeliveryByTime: string;
    DeliveryAddress: string;
    DeliveryAddId: number;
    FFirstName: string;
    FLastName: string;
    FMedicareNo: string;
    FConcessionNo: string;
    FMedicareValidTo: Date;
    FConcessionValidTo: Date;
    Latitude: string;
    Mandtry: string;
    City: string;
    State: string;
    Pincode: string;
    Longitude: string;
    DeliveryUnit: string;
    DeliveryStreetNumber: string;
    DeliveryStreetName: string;
    OrderTo: number;
    OrderId: number;
    PharmacyId: number;
    IsOrderStatus: number;
    Total: number;
    CreatedBy: number;
    ConcessionNo: string;
    IsConvenienceFee: number;
    IsDeliveryFee: number;
    CustomerOffSet: number;
    PharmacyOffSet: number;
    IsProcessOrder: boolean;
    PharmacyNotes: string;

    constructor(userModel?) {
        userModel = userModel || {};
        this.OrderId = userModel.OrderId || 0;
        this.IsProcessOrder = userModel.IsProcessOrder || false;
        this.CreatedBy = userModel.CreatedBy || 0;
        this.PharmacyId = userModel.PharmacyId || 0;
        this.CustomerId = userModel.CustomerId || 0;
        this.CustomerOffSet = userModel.CustomerOffSet || 0;
        this.PharmacyOffSet = userModel.PharmacyOffSet || 0;
        this.IsOrderStatus = 1;
        this.Mandtry = '*';
        this.PharmacyNotes = userModel.PharmacyNotes || "";
        this.ConcessionNo = userModel.ConcessionNo || "";
        this.FirstName = userModel.FirstName || "";
        this.LastName = userModel.LastName || "";
        this.Latitude = userModel.Latitude || "";
        this.Longitude = userModel.Longitude || "";
        this.City = userModel.City || "";
        this.State = userModel.State || "";
        this.Pincode = userModel.Pincode || "";
        this.MobileNo = userModel.MobileNo || "";
        this.EmailId = userModel.EmailId || "";
        this.Dob = userModel.Dob || null;
        this.Age = userModel.Age || '';
        this.MedicareNo = userModel.MedicareNo || "";
        this.MedicareValidTo = userModel.MedicareValidTo || null;
        this.ConcessionValidTo = userModel.ConcessionValidTo || null;
        this.FMedicareValidTo = userModel.FMedicareValidTo || null;
        this.FConcessionValidTo = userModel.FConcessionValidTo || null;
        this.OrderType = userModel.OrderType || 0;
        this.IsPreferredPharmacy = userModel.IsPreferredPharmacy || 0;
        this.IsConvenienceFee = userModel.IsConvenienceFee || 0;
        this.IsDeliveryFee = userModel.IsDeliveryFee || 0;
        this.IsDefault = userModel.IsDefault || 0;
        this.DeliveryAddId = userModel.DeliveryAddId || 0;
        this.DeliveryByDate = userModel.DeliveryByDate || null;
        this.DeliveryByTime = userModel.DeliveryByTime || 0;
        this.DeliveryAddress = userModel.DeliveryAddress || "";
        this.FFirstName = userModel.FFirstName || "";
        this.FLastName = userModel.FLastName || "";
        this.FMedicareNo = userModel.FMedicareNo || "";
        this.FConcessionNo = userModel.FConcessionNo || "";
        this.OrderTo = userModel.OrderTo || 0;
        this.Total = userModel.Total || 0;
    }
}